package model;
// Generated 17-nov-2017 17:18:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {


     private Integer idperfil;
     private String nombreperfil;
     private int activo;
     private String creadopor;
     private Date fechacreacion;

    public Perfiles() {
    }

	
    public Perfiles(int activo, Date fechacreacion) {
        this.activo = activo;
        this.fechacreacion = fechacreacion;
    }
    public Perfiles(String nombreperfil, int activo, String creadopor, Date fechacreacion) {
       this.nombreperfil = nombreperfil;
       this.activo = activo;
       this.creadopor = creadopor;
       this.fechacreacion = fechacreacion;
    }
   
    public Integer getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(Integer idperfil) {
        this.idperfil = idperfil;
    }
    public String getNombreperfil() {
        return this.nombreperfil;
    }
    
    public void setNombreperfil(String nombreperfil) {
        this.nombreperfil = nombreperfil;
    }
    public int getActivo() {
        return this.activo;
    }
    
    public void setActivo(int activo) {
        this.activo = activo;
    }
    public String getCreadopor() {
        return this.creadopor;
    }
    
    public void setCreadopor(String creadopor) {
        this.creadopor = creadopor;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }




}


